# Generated by Django 2.2.6 on 2020-02-28 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20200228_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcategory',
            old_name='name',
            new_name='category',
        ),
    ]
