# Generated by Django 3.0.3 on 2020-03-01 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projectcategoryorderable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcategory',
            old_name='category',
            new_name='category_name',
        ),
    ]
