# Generated by Django 3.0.3 on 2020-03-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20200301_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['name'], 'verbose_name': 'Project Category', 'verbose_name_plural': 'Project Categories'},
        ),
        migrations.RemoveField(
            model_name='projectcategory',
            name='category_name',
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(default='Motion', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='Motion', help_text='A slug to identify projects by this category', max_length=255, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
